# Generated by Django 5.1.2 on 2025-05-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
