# Generated by Django 5.1.2 on 2025-05-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_bank_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manpowermemo',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='manpowermemo',
            name='payment_balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
