# Generated by Django 5.1.2 on 2025-05-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_manpowermemo_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
