# Generated by Django 5.1.2 on 2025-05-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_memo_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='approximate_bill',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='current_cost',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='current_paid',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='final_bill',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
