# Generated by Django 5.1.2 on 2025-05-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_project_approximate_bill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('RUNNING', 'Running'), ('TRIAL', 'Trial Period'), ('CLOSED', 'Closed'), ('OTHER', 'Other')], default='RUNNING', max_length=10, null=True),
        ),
    ]
