# Generated by Django 5.1.2 on 2025-05-13 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_record'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bank',
        ),
    ]
