# Generated by Django 5.1.2 on 2025-05-17 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_delete_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='payment_balance',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
