# Generated by Django 5.1.2 on 2025-05-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_memo_payment_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='manpowermemo',
            name='is_payment_done',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='memo',
            name='is_payment_done',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
