# Generated by Django 5.1.2 on 2025-05-13 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='bank',
            field=models.ForeignKey(blank=True, help_text='Select bank name', null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.bank'),
        ),
    ]
