# Generated by Django 5.1.2 on 2025-05-15 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_delete_bank'),
        ('finance', '0002_alter_bankaccount_bank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('FTGS', 'FTGS'), ('OTHER', 'Other')], max_length=10)),
                ('voucher_no', models.CharField(blank=True, max_length=100, null=True)),
                ('voucher_date', models.DateField(blank=True, null=True)),
                ('receive_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Transaction creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Transaction last updated')),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.bank')),
                ('company_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.bankaccount')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.project')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-voucher_date'],
            },
        ),
    ]
