# Generated by Django 5.1.2 on 2025-05-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='voucher_date',
            field=models.DateField(blank=True, help_text='Example: 2025-12-31', null=True),
        ),
    ]
