# Generated by Django 5.1.2 on 2025-05-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_transaction_voucher_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.PositiveIntegerField(help_text='Maximum allowed is 10,000,000 TK'),
        ),
    ]
