# Generated by Django 5.1.2 on 2025-05-15 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_transaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='bank',
            field=models.ForeignKey(blank=True, help_text='Only fill this if payment is not Cash.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.bank'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='voucher_no',
            field=models.CharField(blank=True, help_text='Only fill this if payment is not Cash.', max_length=100, null=True),
        ),
    ]
