# Generated by Django 5.1.2 on 2025-05-19 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_memo_payment_balance'),
        ('finance', '0006_alter_transaction_bank_alter_transaction_voucher_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenPowerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('FTGS', 'FTGS'), ('OTHER', 'Other')], max_length=20)),
                ('check_number', models.CharField(blank=True, help_text='Only fill this if payment is not Cash.', max_length=100, null=True)),
                ('is_payment_done', models.BooleanField(default=False)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.bankaccount')),
                ('menpowermemo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.manpowermemo')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('FTGS', 'FTGS'), ('OTHER', 'Other')], max_length=20)),
                ('check_number', models.CharField(blank=True, help_text='Only fill this if payment is not Cash.', max_length=100, null=True)),
                ('is_payment_done', models.BooleanField(default=False)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.bankaccount')),
                ('memo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.memo')),
            ],
        ),
    ]
