# Generated by Django 5.1.2 on 2025-05-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_menpowerpayment_supplierpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='menpowerpayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
