# Generated by Django 5.1.2 on 2025-05-24 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_menpowerpayment_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_provider_name', models.CharField(help_text='Name of the person or organization giving the loan', max_length=100)),
                ('loan_giver_type', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank Deposit'), ('MOBILE', 'Bkash / Nogod / Rocket'), ('CHEQUE', 'Cheque')], max_length=10)),
                ('amount', models.PositiveIntegerField()),
                ('payment_amount', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Loan Approved'), ('PAID', 'Payment Done'), ('CLEARED', 'Loan Cleared')], default='PENDING', max_length=10)),
                ('cheque_number', models.CharField(blank=True, max_length=50, null=True)),
                ('cheque_date', models.DateField(blank=True, null=True)),
                ('voucher_number', models.CharField(blank=True, max_length=50, null=True)),
                ('voucher_date', models.DateField(blank=True, null=True)),
                ('receive_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(blank=True, help_text='Linked bank account if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.bankaccount')),
            ],
        ),
    ]
