# Generated by Django 5.1.2 on 2025-05-25 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_type',
            field=models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank Deposit'), ('MOBILE', 'Bkash / Nogod / Rocket'), ('CHEQUE', 'Cheque')], default='SAVINGS', max_length=10),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Loan Approved'), ('PAID', 'Payment Done')], default='PENDING', max_length=10),
        ),
        migrations.CreateModel(
            name='PayLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('payloan_giver_type', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank Deposit'), ('MOBILE', 'Bkash / Nogod / Rocket'), ('CHEQUE', 'Cheque')], max_length=10)),
                ('cheque_number', models.CharField(blank=True, max_length=50, null=True)),
                ('cheque_date', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.bankaccount')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.loan')),
            ],
        ),
    ]
