# Generated by Django 5.1.2 on 2025-05-26 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_alter_loan_payment_amount_alter_loan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payloan',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.bankaccount'),
        ),
    ]
