# Generated by Django 5.1.2 on 2025-05-26 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_alter_payloan_bank_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payloan',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.bankaccount'),
        ),
    ]
