# Generated by Django 5.1.2 on 2025-05-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_alter_payloan_bank_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='voucher_date',
            field=models.DateField(blank=True, help_text='Only fill this if payment is not Cash.', null=True),
        ),
    ]
