# Generated by Django 5.1.2 on 2025-05-26 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_transaction_cheque_date_transaction_cheque_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.bank'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='voucher_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='voucher_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
