# Generated by Django 5.1.2 on 2025-05-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_alter_transaction_bank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menpowerpayment',
            name='type',
            field=models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank Deposit'), ('MOBILE', 'Bkash / Nogod / Rocket'), ('CHEQUE', 'Cheque')], max_length=20),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='type',
            field=models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank Deposit'), ('MOBILE', 'Bkash / Nogod / Rocket'), ('CHEQUE', 'Cheque')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank Deposit'), ('MOBILE', 'Bkash / Nogod / Rocket'), ('CHEQUE', 'Cheque')], max_length=10),
        ),
    ]
