# Generated by Django 5.1.2 on 2025-05-30 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('finance', '0017_alter_menpowerpayment_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevitTransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('payment_type', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank Deposit'), ('MOBILE', 'Bkash / Nogod / Rocket'), ('CHEQUE', 'Cheque')], max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
