# Generated by Django 5.1.2 on 2025-05-30 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_devittransactionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='devittransactionhistory',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.bankaccount'),
        ),
        migrations.AddField(
            model_name='devittransactionhistory',
            name='check_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
