# Generated by Django 5.1.2 on 2025-05-30 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_devittransactionhistory_bank_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devittransactionhistory',
            name='project_or_loan_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
